services:
  backend:
    build: ./backend
    container_name: crm_backend
    ports:
      - "8080:8080"
    networks:
      - crm_network
    env_file:
      - .env
    restart: always

  frontend:
    build: ./frontend
    container_name: crm_frontend
    ports:
      - "3000:80"
    networks:
      - crm_network
    restart: always

networks:
  crm_network: 
    external: ${is_external_network:-false}
    name: ${NETWORK_NAME:-crm_network}